### PR TITLE
Restructures event logic

### PR DESCRIPTION
**Pull request by sagikazarmark**
@rosstuck Planning to release 0.2 after merging this one.

### CODE REVIEW

**Comment by rosstuck** [comment]
No real objections here. Two small notes from my side:
- A user can no longer do `instanceof CommandEvent` to safely verify they can call `getCommand()` anymore.
- I don't know if the separation is really worth the extra inheritance complexity.

Neither of those are major though so of you're satisfied with it though, go for it. :)

**Comment by sagikazarmark** [comment]
The point about the type check is totally valid.

The other one: it is an implementation detail, doesn't matter for a user.

**Comment by sagikazarmark** [comment]
Also, based on [this](http://stackoverflow.com/questions/12478124/how-to-overload-class-constructor-within-traits-in-php-5-4) writting constructors in traits is a bad idea.

**Comment by sagikazarmark** [comment]
@rosstuck Better now?

**Pull request merged**
